# Test from stack overflow

name: Remove console-log
on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: 'onsole\.log\(([^)]+)\)'
          replace: ""
          regex: true